### ISSUE TITLE
setup: accept relative path or enforce absolute path

### ISSUE THREAD

**Issue by juhp** [simeg/eureka#88]
I had a quick play with eureka and thought I would report my initial impressions:

During setup a relative path is accepted (probably anything even).
Then when running eureka it panics with `Could not locate repo at: sdfsdf`.

If possible it might be better just to init a git repo in a default location.
Perhaps there is some cross-platform library that could help with that?
Not sure if making the branch configurable is really needed at setup time (modern git defaults to `main`)?
You could also have a `--clone` option to get a remote repo.

You could use ~/.eureka for configuring an alternative repo location location.

**Comment by simeg** [comment]
Hi @juhp!

Enforcing absolute path sounds easier than trying to figure out a relative path. The path is persisted to disk so it needs to be absolute. I agree that makes sense.

>If possible it might be better just to init a git repo in a default location.

I like that idea -- it can be an optional step during the setup. That would save the user some manual work.

>Not sure if making the branch configurable is really needed at setup time (modern git defaults to main)?

I'm trying to remember why I decided this was a good idea because I can't think of a good reason to have it right now. The program assumes you have a separate repo for your ideas so why should it not assume you're using the default branch? I will default to `main` in an upcoming version.

>You could also have a --clone option to get a remote repo.

Can you expand on this idea?

Apologies for the late response.

**Comment by simeg** [comment]
Thanks again for the good ideas @juhp! I've implemented some of them and created separate issues for the rest. 

- [x] Enforce absolute path during setup (done in #90)
- [x] Default to `main` branch (done in #90 and also proposed in #89)
- [ ] Be able to init repo during setup (#93)
- [ ] Be able to clone repo during setup (#94)

**Comment by juhp** [comment]
Thanks - I may have another play with it later :)
